import type { Metadata } from "next";
import localFont from 'next/font/local';
import Footer from "./_components/Footer";
import Nav from "./_components/Nav";
import "./globals.css";

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: '--font-pretendard',
})

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pretendard.className}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
